FROM node:19-alpine
RUN apk update
RUN apk add git
RUN npm install -g npm@9.6.4
RUN git clone https://github.com/IliyanID/NFT-Marketplace-CS-458.git
RUN cd /NFT-Marketplace-CS-458/frontend && npm install && npm run build

WORKDIR /NFT-Marketplace-CS-458/frontend/build

ENTRYPOINT npx serve -l 3000
EXPOSE 3000