FROM node:14-alpine
RUN apk update
RUN apk add git
RUN npm install -g npm@6.14.15
RUN git clone https://github.com/IliyanID/NFT-Marketplace-CS-458.git
RUN cd /NFT-Marketplace-CS-458/client && npm install && npm run build

WORKDIR /NFT-Marketplace-CS-458/client/build

ENTRYPOINT npx serve -l 3000
EXPOSE 3000